sudo: required

services:
    - docker

before_install:
  - docker build -t abhishekgowda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhishekgowda/docker-react npm run test -- --coverage